-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, (O.SUM * P.PRICE) 'SALES'
FROM PRODUCT P JOIN (
SELECT PRODUCT_ID, SUM(SALES_AMOUNT) 'SUM'
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID) O
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE