-- 코드를 입력하세요
SELECT A.CAR_ID,
CASE WHEN T.CAR_ID IS NULL
THEN '대여 가능'
ELSE '대여중'
END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A LEFT JOIN (SELECT CAR_ID, START_DATE, END_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-10-16' AND DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-10-16'
ORDER BY CAR_ID) AS T
ON A.CAR_ID=T.CAR_ID
GROUP BY A.CAR_ID
ORDER BY A.CAR_ID DESC