-- 코드를 작성해주세요
WITH FISH_GROUP AS (
    SELECT FISH_TYPE, MAX(LENGTH) MAX
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE (I.FISH_TYPE, I.LENGTH) IN (SELECT * FROM FISH_GROUP)
ORDER BY I.ID