-- 코드를 작성해주세요

SELECT T.SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E JOIN HR_GRADE G JOIN
(
    SELECT EMP_NO, SUM(SCORE) SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
) T
ON E.EMP_NO = G.EMP_NO AND G.EMP_NO = T.EMP_NO
WHERE E.EMP_NO = G.EMP_NO 
LIMIT 1